module.exports = {
    CHALLENGEE: 1,
    VALIDATOR: 2,
    GYFTER: 3,
    GYFTEE: 4,
    GYFT_EVENT: 5,
    LIQUIDITY_REWARD: 6,
    EXCHANGE_WITHDRAW: 7,
    EXCHANGE_TRADE: 8,
    MARKET_MAKER_FEE: 9,
    EOS_ACCOUNT_CREATION_REIMBURSEMENT: 10,
};